# Generated by Django 6.0.5 on 2026-05-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_emissionrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='scope',
            field=models.CharField(choices=[('SCOPE1', 'Scope 1'), ('SCOPE2', 'Scope 2'), ('SCOPE3', 'Scope 3')], default='SCOPE1', max_length=20),
        ),
    ]
