# Generated by Django 6.0.5 on 2026-05-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_emissionrecord_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='normalized_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='normalized_unit',
            field=models.CharField(default='L', max_length=20),
        ),
    ]
