# Generated by Django 6.0.5 on 2026-05-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_emissionrecord_normalized_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
